# If the package is installed already Ansible won't install it again
- name: install epel
  yum:
    # Package name
    name: epel-release
    # Install - in Ansible it is named present - or remove the package
    state: present
  # We can run tasks that contains only given tag.
  tags: [nginx]

- name: install nginx
  yum:
    name: "{{ nginx_service_name }}"
    state: present
  tags: [nginx]

- name: enable nginx
  service:
    name: "{{ nginx_service_name }}"
    state: started
  tags: [nginx, status]

- name: copy nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    # chown
    owner: root
    # chown
    group: root
    # chmod, or use the numeric way
    # mode: 0644
    mode: u=rw,g=r,o=r
  # notifier name, no restrictions, it's just a string.
  notify: restart nginx
  tags: [nginx, config]
